//The Jenkinsfile runs entire build in a golang container and mounts the /var/run/docker.sock file to allow access to the host docker within the container
docker.image('golang:1.15-buster').inside('-u root -v /var/run/docker.sock:/var/run/docker.sock') {
    stage ('Install Docker Client') {
        sh "apt-get update"
        sh '''
           apt-get install -y \
           apt-transport-https \
           ca-certificates \
           curl \
           gnupg-agent \
           software-properties-common
        '''
        sh "curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -"
        sh '''
           add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/debian \
           $(lsb_release -cs) \
           stable"
        '''
        sh "apt-get update && apt-get install -y docker-ce-cli"
    }
    stage ('Install yq') {
        sh "wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/download/2.1.2/yq_linux_amd64"
        sh "chmod 555 /usr/bin/yq"
    }
    stage ('Checkout SCM') {
        checkout scm
    }
}