//The Jenkinsfile runs entire build in a golang container and mounts the /var/run/docker.sock file to allow access to the host docker within the container
node('wcm') {
    docker.image('golang:1.15-buster').inside('-u root --net=host -v /var/run/docker.sock:/var/run/docker.sock') {
        environment{
            CGO_ENABLED = 0
            GO111MODULE = on
        }
        stage ('Install Docker Client') {
            sh "apt-get update"
            sh '''
               apt-get install -y \
               apt-transport-https \
               ca-certificates \
               curl \
               gnupg-agent \
               software-properties-common
            '''
            sh "curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -"
            sh '''
               add-apt-repository \
               "deb [arch=amd64] https://download.docker.com/linux/debian \
               $(lsb_release -cs) \
               stable"
            '''
            sh "apt-get update && apt-get install -y docker-ce-cli"
        }
        stage ('Install yq') {
            sh "wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/download/2.1.2/yq_linux_amd64"
            sh "chmod 555 /usr/bin/yq"
        }
        stage ('Install kubectl') {
            sh "curl -LO https://storage.googleapis.com/kubernetes-release/release/\"\$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)\"/bin/linux/amd64/kubectl"
            sh "chmod +x kubectl && mv kubectl /usr/local/bin/"
        }
        stage ('Install Helm') {
            sh "curl -LO https://git.io/get_helm.sh"
            sh "chmod 700 get_helm.sh"
            sh "./get_helm.sh"
        }
        stage ('Install kind') {
            sh "curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64"
            sh "chmod +x ./kind"
            sh "mv ./kind /usr/bin/kind"
//             sh "GO111MODULE=\"on\" go get -u sigs.k8s.io/kind@v0.8.1"
        }
        stage ('Checkout SCM') {
            checkout scm
        }
        stage ('Install cloudtest v0.2.0') {
            sh "GO111MODULE=\"on\" go get github.com/networkservicemesh/cloudtest@v0.2.0"
        }
        stage ('Run tests') {
            sh "cloudtest"
        }
        stage ('Cleanup kind clusters') {
            sh "docker ps -a"
        }
    }
}